blank_issues_enabled: false # Desabilita issues em branco, forçando o uso de templates
contact_links:
  - name: 💬 Discussões da Comunidade Hallyutoons
    url: https://github.com/REEDScx/hallyutoons-catalog/discussions
    about: Por favor, use as Discussões para perguntas gerais, ideias ou para conversar com a comunidade.
  - name: 📖 Documentação Hallyutoons (se houver)
    url: https://hallyutoons.site # Ou link para uma Wiki, se você criar uma
    about: Verifique nossa documentação para FAQs e guias.
